// constants/strings.ts
// All UI label strings in PT and EN. Use useStrings() in components.

import { useGameStore } from '../hooks/use-game-store';

const STRINGS = {
    pt: {
        home: {
            apps: {
                zep:       'ZepZep',
                bacen:     'BaCen',
                laranjas:  'Laranjas',
                calendario:'Calendário',
                carteira:  'Cofre',
                dossie:    'Dossiê',
                news:      'News',
                settings:  'Config',
            },
        },
        zep: {
            wordmark:          'ZEP',
            searchPlaceholder: 'Buscar conversa...',
            timeLabel:         'agora',
            checkmarks:        '✓✓ ',
        },
        chat: {
            bagAccept:      'OK, manda.',
            bagDecline:     'Não agora.',
            bagAcceptLater: 'Pronto, pode mandar',
            escalation1:    'E aí? Vai movimentar ou não?',
            escalation2:    'Tô perdendo a paciência. Manda logo.',
        },
        laranjas: {
            appName:         'laranjas',
            ctaBtn:          'CRIAR CARTEIRA DE CRÉDITO',
            warning:         '⚠ aumenta suspeita',
            labelCpfAvail:   'CPF disponíveis',
            processingTitle: 'Criando empréstimos nos nomes da lista. Amalgando pedidos. Gerando ',
            processingLabel: 'PROCESSANDO DÍVIDA E INTEGRANDO AO PRODUTO',
            successTitle:    'CARTEIRA CRIADA',
            successSub:      'Pronto para venda no BACEN',
            btnDias:         (n: number) => `~${n} dias`,
        },
        bacen: {
            wordmark:        'BACEN',
            corpBadge:       'Gov. Federal',
            subtitle:        'Plataforma Interbancária',
            offerBtn:        'OFERECER CARTEIRA',
            sectionLoading:  'BUSCANDO OFERTAS',
            loadingHint:     'Procurando ofertas de outros bancos...',
            sectionOffers:   'OFERTAS RECEBIDAS',
            bankIcon:        'B',
            offerLabel:      'OFERTA',
            cancelLink:      'Cancelar',
            sectionPackList: 'CRÉDITO EM CARTEIRA',
            emptyPacks:      'Nenhuma carteira disponível.',
            confirmBtn:      'CESSAR CARTEIRA DE CRÉDITO',
            bestOffer:       'MELHOR OFERTA',
            bankReady:       'RESPONDEU',
            bankWaiting:     'aguardando...',
            successIcon:     '✓',
            successTitle:    'CARTEIRA VENDIDA',
            successSub:      'Dinheiro limpo adicionado à carteira',
            packName:        (cpfsUsed: number) => `Derivativo — ${cpfsUsed} CPF`,
            packMeta:        (dayCreated: number) => `Emitido dia ${dayCreated} · vence dia ${dayCreated + 90}`,
            packDays:        (days: number) => `${days} dias`,
            auctionPending:  (days: number) => `leilão em andamento — ${days} dia${days === 1 ? '' : 's'}`,
            auctionReady:    'proposta disponível',
            auctionClaim:    'RECEBER',
            auctionStart:    'iniciar leilão',
            auctionPick:     'escolher duração',
        },
        carteira: {
            appName:         'COFRE',
            currency:        'R$',
            labelDirty:      'sujo',
            labelClean:      'limpo',
            sectionTransfer: 'TRANSFERIR PARA PCC',
            labelEnviar:     'enviar',
            labelDoLimpo:    ' do limpo',
            labelAEnviar:    'a enviar',
            labelResta:      (remaining: string) => `resta R$ ${remaining} limpo`,
            maxBtn:          'MAX',
            sendBtn:         'ENVIAR',
            sectionHistory:  'HISTÓRICO',
        },
        payModal: {
            title:      'PAGAR PCC',
            labelBalance: (amount: string) => `Saldo Limpo: ${amount}`,
            btnConfirm: 'CONFIRMAR PAGAMENTO',
            btnCancel:  'Cancelar',
        },
        tutorial: {
            tapToContinue: '(Toque para continuar)',
        },
        levelUp: {
            label:          'NÍVEL',
            tapToPlay:      'TOQUE PARA JOGAR',
            tapToContinue:  'TOQUE PARA CONTINUAR',
        },
        gameOver: {
            masterDays: (days: number) => `Dias como O Mestre: ${days}`,
            restartBtn: 'NOVA PARTIDA',
        },
        dossie: {
            header:          'DOSSIÊ CONFIDENCIAL',
            badge:           'RESTRITO',
            sectionFinancial:'FINANCEIRO',
            sectionContacts: 'CONTATOS',
            rowReceived:     'Total recebido',
            rowPaid:         'Total pago PCC',
            rowDirty:        'Sujo em caixa',
            rowClean:        'Limpo em caixa',
            rowCpfs:         'CPFs disponíveis',
            statusPending:   'Pendente',
            statusWaiting:   'Aguardando',
            statusActive:    'Ativo',
            statusUrgent:    'Urgente',
            statusDone:      'Concluído',
            statusResolved:  'Resolvido',
        },
        settings: {
            title:      'idioma / language',
            langPt:     'PT 🇧🇷',
            langEn:     'EN 🇺🇸',
        },
    },
    en: {
        home: {
            apps: {
                zep:       'ZepZep',
                bacen:     'BaCen',
                laranjas:  'Laranjas',
                calendario:'Calendar',
                carteira:  'Safe',
                dossie:    'Dossier',
                news:      'News',
                settings:  'Settings',
            },
        },
        zep: {
            wordmark:          'ZEP',
            searchPlaceholder: 'Search conversation...',
            timeLabel:         'now',
            checkmarks:        '✓✓ ',
        },
        chat: {
            bagAccept:      'OK, send it.',
            bagDecline:     'Not now.',
            bagAcceptLater: 'Ready, go ahead',
            escalation1:    'Well? Moving it or not?',
            escalation2:    'Running out of patience. Send it now.',
        },
        laranjas: {
            appName:         'laranjas',
            ctaBtn:          'CREATE CREDIT PORTFOLIO',
            warning:         '⚠ increases suspicion',
            labelCpfAvail:   'CPFs available',
            processingTitle: 'Creating loans under listed names. Merging requests. Generating ',
            processingLabel: 'PROCESSING DEBT AND INTEGRATING INTO PRODUCT',
            successTitle:    'PORTFOLIO CREATED',
            successSub:      'Ready for sale at BACEN',
            btnDias:         (n: number) => `~${n} days`,
        },
        bacen: {
            wordmark:        'BACEN',
            corpBadge:       'Gov. Federal',
            subtitle:        'Interbank Platform',
            offerBtn:        'OFFER PORTFOLIO',
            sectionLoading:  'SEARCHING OFFERS',
            loadingHint:     'Looking for offers from other banks...',
            sectionOffers:   'OFFERS RECEIVED',
            bankIcon:        'B',
            offerLabel:      'OFFER',
            cancelLink:      'Cancel',
            sectionPackList: 'CREDIT IN PORTFOLIO',
            emptyPacks:      'No portfolio available.',
            confirmBtn:      'SETTLE CREDIT PORTFOLIO',
            bestOffer:       'BEST OFFER',
            bankReady:       'RESPONDED',
            bankWaiting:     'waiting...',
            successIcon:     '✓',
            successTitle:    'PORTFOLIO SOLD',
            successSub:      'Clean money added to wallet',
            packName:        (cpfsUsed: number) => `Derivative — ${cpfsUsed} CPF`,
            packMeta:        (dayCreated: number) => `Issued day ${dayCreated} · due day ${dayCreated + 90}`,
            packDays:        (days: number) => `${days} day${days === 1 ? '' : 's'}`,
            auctionPending:  (days: number) => `auction in progress — ${days} day${days === 1 ? '' : 's'}`,
            auctionReady:    'offer available',
            auctionClaim:    'CLAIM',
            auctionStart:    'start auction',
            auctionPick:     'choose duration',
        },
        carteira: {
            appName:         'SAFE',
            currency:        'R$',
            labelDirty:      'sujo',
            labelClean:      'limpo',
            sectionTransfer: 'TRANSFER TO PCC',
            labelEnviar:     'send',
            labelDoLimpo:    ' of clean',
            labelAEnviar:    'to send',
            labelResta:      (remaining: string) => `R$ ${remaining} clean left`,
            maxBtn:          'MAX',
            sendBtn:         'SEND',
            sectionHistory:  'HISTORY',
        },
        payModal: {
            title:      'PAY PCC',
            labelBalance: (amount: string) => `Clean Balance: ${amount}`,
            btnConfirm: 'CONFIRM PAYMENT',
            btnCancel:  'Cancel',
        },
        tutorial: {
            tapToContinue: '(Tap to continue)',
        },
        levelUp: {
            label:          'LEVEL',
            tapToPlay:      'TAP TO PLAY',
            tapToContinue:  'TAP TO CONTINUE',
        },
        gameOver: {
            masterDays: (days: number) => `Days as O Mestre: ${days}`,
            restartBtn: 'NEW GAME',
        },
        dossie: {
            header:          'CONFIDENTIAL DOSSIER',
            badge:           'RESTRICTED',
            sectionFinancial:'FINANCIAL',
            sectionContacts: 'CONTACTS',
            rowReceived:     'Total received',
            rowPaid:         'Total paid PCC',
            rowDirty:        'Dirty on hand',
            rowClean:        'Clean on hand',
            rowCpfs:         'CPFs available',
            statusPending:   'Pending',
            statusWaiting:   'Waiting',
            statusActive:    'Active',
            statusUrgent:    'Urgent',
            statusDone:      'Done',
            statusResolved:  'Resolved',
        },
        settings: {
            title:      'idioma / language',
            langPt:     'PT 🇧🇷',
            langEn:     'EN 🇺🇸',
        },
    },
} as const;

export type Strings = typeof STRINGS.pt;

export function useStrings(): Strings {
    const language = useGameStore(s => s.language);
    return STRINGS[language] as Strings;
}
